{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import turtle\n",
    "import math\n",
    "\n",
    "Sun = turtle.Turtle()\n",
    "Sun.shape(\"circle\")\n",
    "Sun.color(\"yellow\")\n",
    "\n",
    "Mercury = turtle.Turtle()\n",
    "a1 = 70\n",
    "b1 = 68\n",
    "c1 = (a1**2-b1**2)**0.5\n",
    "Mercury.shape(\"circle\")\n",
    "Mercury.speed(0)\n",
    "Mercury.color('blue')\n",
    "Mercury.penup()\n",
    "Mercury.goto ((a1-c1),0)\n",
    "Mercury.pendown()\n",
    "\n",
    "Venus = turtle.Turtle()\n",
    "a2 = 110\n",
    "b2 = 105\n",
    "c2 = (a2**2-b2**2)**0.5\n",
    "Venus.shape(\"circle\")\n",
    "Venus.speed(0)\n",
    "Venus.color('orange')\n",
    "Venus.penup()\n",
    "Venus.goto (a2-c2,0)\n",
    "Venus.pendown()\n",
    "\n",
    "Earth = turtle.Turtle()\n",
    "a3 = 140\n",
    "b3 = 135\n",
    "c3 = (a3**2-b3**2)**0.5\n",
    "Earth.shape(\"circle\")\n",
    "Earth.speed(0)\n",
    "Earth.color('sea green')\n",
    "Earth.penup()\n",
    "Earth.goto (a3-c3,0)\n",
    "Earth.pendown()\n",
    "\n",
    "Mars = turtle.Turtle()\n",
    "a4 = 170\n",
    "b4 = 165\n",
    "c4 = (a4**2-b4**2)**0.5\n",
    "Mars.shape(\"circle\")\n",
    "Mars.speed(0)\n",
    "Mars.color('red')\n",
    "Mars.penup()\n",
    "Mars.goto (a4-c4,0)\n",
    "Mars.pendown()\n",
    "\n",
    "Jupiter = turtle.Turtle()\n",
    "a5 = 200\n",
    "b5 = 195\n",
    "c5 = (a5**2-b5**2)**0.5\n",
    "Jupiter.shape(\"circle\")\n",
    "Jupiter.speed(0)\n",
    "Jupiter.color('purple')\n",
    "Jupiter.penup()\n",
    "Jupiter.goto (a5-c5,0)\n",
    "Jupiter.pendown()\n",
    "\n",
    "Saturn = turtle.Turtle()\n",
    "a6 = 230\n",
    "b6 = 225\n",
    "c6 = (a6**2-b6**2)**0.5\n",
    "Saturn.shape(\"circle\")\n",
    "Saturn.speed(0)\n",
    "Saturn.color('brown')\n",
    "Saturn.penup()\n",
    "Saturn.goto (a6-c6,0)\n",
    "Saturn.pendown()\n",
    "\n",
    "for angle in range(3600):\n",
    "    \n",
    "    x1 = a1*math.cos(math.radians(angle))-c1\n",
    "    y1 = b1*math.sin(math.radians(angle))\n",
    "    Mercury.goto (x1,y1)\n",
    "    \n",
    "    x2 = a2*math.cos(math.radians(angle*0.85))-c2\n",
    "    y2 = b2*math.sin(math.radians(angle*0.85))\n",
    "    Venus.goto (x2,y2)\n",
    "    \n",
    "    x3 = a3*math.cos(math.radians(angle*0.7))-c3\n",
    "    y3 = b3*math.sin(math.radians(angle*0.7))\n",
    "    Earth.goto (x3,y3)\n",
    "    \n",
    "    x4 = a4*math.cos(math.radians(angle*0.5))-c4\n",
    "    y4 = b4*math.sin(math.radians(angle*0.5))\n",
    "    Mars.goto (x4,y4)\n",
    "    \n",
    "    x5 = a5*math.cos(math.radians(angle*0.35))-c5\n",
    "    y5 = b5*math.sin(math.radians(angle*0.35))\n",
    "    Jupiter.goto (x5,y5)\n",
    "    \n",
    "    x6 = a6*math.cos(math.radians(angle*0.2))-c6\n",
    "    y6 = b6*math.sin(math.radians(angle*0.2))\n",
    "    Saturn.goto (x6,y6)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
